import { Product } from './interfaces';

export const Products: Product[] = [
  {
    productName: 'Wireless Bluetooth Headphones',
    description:
      'High-quality sound with noise cancellation. Comfortable design with over-ear pads.',
    category: 'Electronics > Audio',
    price: '$99.99',
    stock: '150 units',
    brand: 'SoundPro',
    rating: '4.5/5 (250 reviews)',
    features:
      'Bluetooth 5.0, 30 hours battery life, Built-in microphone for calls',
    images: 'Image1, Image2, Image3',
  },
  {
    productName: 'Organic Cotton T-Shirt',
    description:
      'Soft, breathable, and eco-friendly. Perfect for everyday wear.',
    category: 'Clothing > Men > T-Shirts',
    price: '$19.99',
    stock: '200 units',
    brand: 'EcoWear',
    rating: '4.8/5 (180 reviews)',
    features: 'S, M, L, XL sizes; White, Black, Navy colors',
    images: 'Image1, Image2, Image3',
    size: 'S, M, L, XL',
    color: 'White, Black, Navy',
    materials: '100% Organic Cotton',
    careInstructions: 'Machine wash cold, tumble dry low',
  },
  {
    productName: 'Stainless Steel Water Bottle',
    description: 'Leak-proof, BPA-free, keeps beverages hot or cold for hours.',
    category: 'Home & Kitchen > Drinkware',
    price: '$25.50',
    stock: '300 units',
    brand: 'HydroMax',
    rating: '4.7/5 (95 reviews)',
    features:
      'Insulated double-wall design, Wide mouth for easy filling and cleaning',
    images: 'Image1, Image2, Image3',
    capacity: '500ml, 750ml',
    color: 'Silver, Matte Black',
    materials: 'Stainless Steel',
  },
  {
    productName: 'Adjustable Office Chair',
    description:
      'Ergonomic office chair with lumbar support, adjustable armrests, and height.',
    category: 'Furniture > Office Chairs',
    price: '$149.99',
    stock: '50 units',
    brand: 'WorkComfort',
    rating: '4.2/5 (30 reviews)',
    features: '360-degree swivel, Tilt and recline function',
    images: 'Image1, Image2, Image3',
    dimensions: '22” x 22” x 45”',
    materials: 'Mesh, PU leather',
  },
  {
    productName: 'Smart LED Desk Lamp',
    description:
      'Dimmable LED desk lamp with touch controls and color temperature adjustment.',
    category: 'Home & Living > Lighting',
    price: '$39.99',
    stock: '75 units',
    brand: 'LightUp',
    rating: '4.6/5 (120 reviews)',
    features: 'Adjustable brightness and color temperature, USB charging port',
    images: 'Image1, Image2, Image3',
    color: 'White, Black',
    power: '12W',
  },
  {
    productName: '4K Ultra HD Smart TV',
    description:
      '65-inch smart TV with 4K resolution and built-in voice assistant.',
    category: 'Electronics > TVs & Entertainment',
    price: '$799.99',
    stock: '30 units',
    brand: 'VisionTech',
    rating: '4.7/5 (220 reviews)',
    features: '4K Ultra HD, Voice control, Smart TV with built-in apps',
    images: 'Image1, Image2, Image3',
  },
  {
    productName: 'Portable Power Bank',
    description:
      '20,000mAh portable charger with fast charging and multiple USB ports.',
    category: 'Electronics > Power & Charging',
    price: '$39.99',
    stock: '100 units',
    brand: 'PowerMax',
    rating: '4.6/5 (180 reviews)',
    features: 'Fast charging, 20,000mAh capacity, 3 USB ports',
    images: 'Image1, Image2, Image3',
    capacity: '20,000mAh',
    color: 'Black, White',
  },
  {
    productName: 'Leather Wallet',
    description:
      'Genuine leather wallet with multiple card slots and a money clip.',
    category: 'Accessories > Wallets & Bags',
    price: '$29.99',
    stock: '200 units',
    brand: 'LeatherCraft',
    rating: '4.8/5 (150 reviews)',
    features: 'Genuine leather, Multiple card slots, Money clip',
    images: 'Image1, Image2, Image3',
    color: 'Brown, Black',
  },
  {
    productName: 'Electric Coffee Maker',
    description:
      '12-cup coffee maker with programmable timer and stainless steel finish.',
    category: 'Home & Kitchen > Coffee Makers',
    price: '$49.99',
    stock: '80 units',
    brand: 'BrewMaster',
    rating: '4.3/5 (75 reviews)',
    features: '12-cup capacity, Programmable timer, Stainless steel design',
    images: 'Image1, Image2, Image3',
    power: '1000W',
  },
  {
    productName: 'Gaming Laptop',
    description:
      'High-performance laptop with NVIDIA graphics and 16GB RAM for gaming.',
    category: 'Electronics > Laptops',
    price: '$1,299.99',
    stock: '50 units',
    brand: 'TechPro',
    rating: '4.9/5 (180 reviews)',
    features: 'NVIDIA GTX 1660, 16GB RAM, 512GB SSD, 15.6-inch display',
    images: 'Image1, Image2, Image3',
    color: 'Black, Silver',
  },
  {
    productName: 'Ceramic Flower Vase',
    description:
      'Handmade ceramic vase perfect for home decoration or as a gift.',
    category: 'Home & Living > Decor',
    price: '$19.99',
    stock: '120 units',
    brand: 'HomeArt',
    rating: '4.5/5 (65 reviews)',
    features: 'Handmade ceramic, Elegant design, Perfect for flowers',
    images: 'Image1, Image2, Image3',
    color: 'White, Blue, Green',
  },
  {
    productName: 'Electric Toothbrush',
    description:
      'Sonic electric toothbrush with multiple cleaning modes and a long battery life.',
    category: 'Health & Beauty > Oral Care',
    price: '$39.99',
    stock: '200 units',
    brand: 'CleanPro',
    rating: '4.6/5 (200 reviews)',
    features: 'Sonic cleaning, 3 modes, Long battery life, Rechargeable',
    images: 'Image1, Image2, Image3',
  },
  {
    productName: 'Camping Tent',
    description: '4-person waterproof tent with easy setup and ventilation.',
    category: 'Sports & Outdoors > Camping',
    price: '$79.99',
    stock: '60 units',
    brand: 'AdventureGear',
    rating: '4.4/5 (95 reviews)',
    features: 'Waterproof, 4-person capacity, Easy setup, Ventilation windows',
    images: 'Image1, Image2, Image3',
    dimensions: '120” x 120” x 80”',
  },
  {
    productName: 'Smart Fitness Tracker',
    description:
      'Monitor your heart rate, steps, sleep, and more with this advanced fitness tracker.',
    category: 'Health & Beauty > Fitness',
    price: '$49.99',
    stock: '150 units',
    brand: 'FitTrack',
    rating: '4.7/5 (300 reviews)',
    features:
      'Heart rate monitor, Step counter, Sleep tracking, Water-resistant',
    images: 'Image1, Image2, Image3',
    color: 'Black, Blue, Pink',
  },
  {
    productName: 'Adjustable Dumbbells',
    description:
      'Set of adjustable dumbbells for home workouts. Weight range from 5 to 52.5 lbs.',
    category: 'Sports & Outdoors > Fitness',
    price: '$149.99',
    stock: '80 units',
    brand: 'PowerLift',
    rating: '4.5/5 (120 reviews)',
    features: 'Adjustable weight, Durable design, Easy to switch weights',
    images: 'Image1, Image2, Image3',
    color: 'Black',
  },
  {
    productName: 'Smart Wi-Fi Thermostat',
    description:
      'Control your home temperature remotely with this Wi-Fi enabled thermostat.',
    category: 'Home & Living > Smart Home',
    price: '$129.99',
    stock: '100 units',
    brand: 'HomeSmart',
    rating: '4.6/5 (200 reviews)',
    features:
      'Wi-Fi enabled, Energy-saving, Voice control with Alexa and Google Assistant',
    images: 'Image1, Image2, Image3',
    color: 'White',
  },
  {
    productName: 'Non-stick Cookware Set',
    description:
      '10-piece non-stick cookware set, ideal for all stovetops and dishwasher safe.',
    category: 'Home & Kitchen > Cookware',
    price: '$89.99',
    stock: '50 units',
    brand: 'CookPro',
    rating: '4.4/5 (85 reviews)',
    features: 'Non-stick surface, Dishwasher safe, Durable',
    images: 'Image1, Image2, Image3',
    color: 'Black',
  },
  {
    productName: 'Robot Vacuum Cleaner',
    description:
      'Automatic vacuum cleaner with smart navigation and voice control integration.',
    category: 'Home & Living > Vacuums',
    price: '$299.99',
    stock: '40 units',
    brand: 'CleanBot',
    rating: '4.8/5 (150 reviews)',
    features: 'Smart navigation, Voice control, Automatic charging',
    images: 'Image1, Image2, Image3',
    color: 'Black',
  },
  {
    productName: 'Wine Cooler Refrigerator',
    description:
      'Compact wine cooler with adjustable shelves and temperature control.',
    category: 'Home & Kitchen > Refrigeration',
    price: '$199.99',
    stock: '60 units',
    brand: 'ChillMax',
    rating: '4.5/5 (50 reviews)',
    features: 'Adjustable shelves, Temperature control, Quiet operation',
    images: 'Image1, Image2, Image3',
    capacity: '18 bottles',
  },
  {
    productName: 'Luxury Bed Linen Set',
    description:
      'High-quality 100% cotton 4-piece bed linen set with a luxurious feel.',
    category: 'Home & Living > Bedding',
    price: '$59.99',
    stock: '150 units',
    brand: 'SleepWell',
    rating: '4.9/5 (250 reviews)',
    features: '100% cotton, Soft and breathable, Machine washable',
    images: 'Image1, Image2, Image3',
    size: 'Queen, King',
  },
  {
    productName: 'Outdoor BBQ Grill',
    description:
      'Portable 3-burner gas grill with side shelves and a large cooking surface.',
    category: 'Sports & Outdoors > BBQ & Grilling',
    price: '$249.99',
    stock: '30 units',
    brand: 'GrillMaster',
    rating: '4.6/5 (95 reviews)',
    features: '3 burners, Side shelves, Large cooking surface, Portable',
    images: 'Image1, Image2, Image3',
    color: 'Silver',
  },
  {
    productName: 'Smart Home Security Camera',
    description:
      'HD security camera with night vision and motion detection, compatible with Alexa and Google Assistant.',
    category: 'Electronics > Smart Home',
    price: '$89.99',
    stock: '120 units',
    brand: 'SafeGuard',
    rating: '4.8/5 (400 reviews)',
    features: 'Motion detection, Night vision, Cloud storage, 1080p HD video',
    images: 'Image1, Image2, Image3',
    color: 'White, Black',
  },
  {
    productName: 'Cordless Electric Kettle',
    description:
      '1.7L cordless electric kettle with rapid boiling and auto shut-off feature.',
    category: 'Home & Kitchen > Kitchen Appliances',
    price: '$29.99',
    stock: '150 units',
    brand: 'HeatMaster',
    rating: '4.7/5 (180 reviews)',
    features: 'Rapid boiling, Auto shut-off, 1.7L capacity',
    images: 'Image1, Image2, Image3',
    color: 'Stainless Steel, Black',
  },
  {
    productName: 'Noise-Cancelling Earbuds',
    description:
      'True wireless earbuds with noise cancellation and up to 8 hours of playtime.',
    category: 'Electronics > Audio',
    price: '$59.99',
    stock: '100 units',
    brand: 'SoundSphere',
    rating: '4.6/5 (200 reviews)',
    features: 'Active noise cancellation, 8 hours playtime, Touch control',
    images: 'Image1, Image2, Image3',
    color: 'Black, White',
  },
  {
    productName: 'Electric Standing Desk',
    description:
      'Adjustable electric standing desk with memory presets and a spacious work surface.',
    category: 'Furniture > Office Furniture',
    price: '$299.99',
    stock: '50 units',
    brand: 'StandUpTech',
    rating: '4.9/5 (95 reviews)',
    features: 'Electric height adjustment, Memory presets, Large work surface',
    images: 'Image1, Image2, Image3',
    color: 'Black, White',
  },
  {
    productName: 'Digital Meat Thermometer',
    description:
      'Instant-read digital thermometer for cooking, grilling, and baking.',
    category: 'Home & Kitchen > Kitchen Tools',
    price: '$14.99',
    stock: '300 units',
    brand: 'CookMate',
    rating: '4.5/5 (250 reviews)',
    features: 'Instant-read, Waterproof, High accuracy',
    images: 'Image1, Image2, Image3',
    color: 'Silver, Black',
  },
  {
    productName: '3-in-1 Hair Dryer & Volumizer',
    description:
      'Hair dryer and volumizer that smoothens, dries, and adds volume in one step.',
    category: 'Health & Beauty > Hair Care',
    price: '$49.99',
    stock: '180 units',
    brand: 'BeautyFlow',
    rating: '4.4/5 (120 reviews)',
    features: 'Hair drying, Volumizing, Ceramic coating, 3 heat settings',
    images: 'Image1, Image2, Image3',
    color: 'Pink, Black',
  },
  {
    productName: 'Touchscreen Smartwatch',
    description:
      'Smartwatch with fitness tracking, heart rate monitor, and customizable watch faces.',
    category: 'Electronics > Wearables',
    price: '$89.99',
    stock: '150 units',
    brand: 'TimeTech',
    rating: '4.7/5 (300 reviews)',
    features:
      'Fitness tracking, Heart rate monitor, 10-day battery life, Customizable watch faces',
    images: 'Image1, Image2, Image3',
    color: 'Black, Silver, Rose Gold',
  },
  {
    productName: 'High-Speed Blender',
    description:
      'Powerful blender with stainless steel blades, perfect for smoothies, soups, and more.',
    category: 'Home & Kitchen > Blenders',
    price: '$129.99',
    stock: '60 units',
    brand: 'BlendMaster',
    rating: '4.5/5 (85 reviews)',
    features: 'High-speed motor, Stainless steel blades, Easy to clean',
    images: 'Image1, Image2, Image3',
    color: 'Black, Silver',
  },
];
